import dynamic from "next/dynamic";

export const content = {
  nav: {
    home: 'Home',
    about: 'About',
    qualification: 'Qualifications',
    portfolio: 'Portfolio',
    contact: 'Contact',
    loading: 'Loading...'
  },
  hero: {
    greeting: 'Hello, I am',
    name: 'Julian F. Lancheros',
    title: 'AgTech Engineer & Developer',
    description: 'I transform agricultural data noise into profitability. I build the digital infrastructure that scales the agribusiness industry through Code, GIS and Cloud.',
    cta: 'View Projects',
    ctaSecondary: 'Contact Me',
    dynamicTexts: [
      'programming',
      'design',
      'nature',
      'engineering',
      'web design',
      'agriculture',
      'IoT and cloud',
      'learning new things...'
    ]
  },
  about: {
    title: 'My mission',
    subtitle: 'Learn more about my journey',
    profileTitle: 'Agricultural Engineer: Digitalizing the field with Scalable Infrastructure and GIS.',
    profileDescription: `Don't choose between an agronomist and a developer. Have both. <br><br>

I operate at the exact intersection where <b>Agricultural Engineering</b> meets the <b>Cloud</b>. Unlike a traditional dev, I understand crop physiology and soil variability; and unlike a classic engineer, I have the technical capacity to build the <b>digital infrastructure</b> that scales the business. <br><br>

My obsession is simple: Transform the terabytes of "noise" generated by the field into <b>profitability</b> and precise agronomic decisions.`,
    city: 'City',
    cityValue: 'Bogotá, CO',
    degree: 'Degree',
    degreeValue: 'Undergraduate student',
    finalPhrase: 'I seek opportunities where I can get my boots dirty with field data and clean them by writing efficient code'
  },
  interests: {
    title: 'Interests',
    items: [
      { name: 'Geomatics', icon: 'radar' },
      { name: 'Statistics', icon: 'chart' },
      { name: 'Programming', icon: 'code' },
      { name: 'Design', icon: 'brush' },
      { name: 'Databases', icon: 'database' },
      { name: 'Logistics and Machinery', icon: 'truck' },
      { name: 'Digital Marketing', icon: 'store' },
      { name: 'Nature', icon: 'leaf' }
    ]
  },
  skills: {
    title: 'Skills',
    categories: [
      {
        name: 'Frontend',
        items: [
          { name: 'HTML5/CSS3', level: 90 },
          { name: 'JavaScript/TypeScript', level: 85 },
          { name: 'React/Next.js', level: 80 },
          { name: 'Tailwind CSS', level: 85 }
        ]
      },
      {
        name: 'Backend',
        items: [
          { name: 'Node.js', level: 75 },
          { name: 'Python', level: 80 },
          { name: 'Google Apps Script', level: 85 },
          { name: 'Databases', level: 70 }
        ]
      },
      {
        name: 'GIS & Data',
        items: [
          { name: 'QGIS', level: 85 },
          { name: 'ArcGIS', level: 75 },
          { name: 'R', level: 70 },
          { name: 'Data Analysis', level: 80 }
        ]
      },
      {
        name: 'Others',
        items: [
          { name: 'Git/GitHub', level: 85 },
          { name: 'Joomla/WordPress', level: 75 },
          { name: 'IoT', level: 65 },
          { name: 'C++/Java', level: 70 }
        ]
      }
    ]
  },
  qualification: {
    title: 'Qualifications',
    subtitle: 'My personal journey',
    experience: 'Professional Experience',
    education: 'Education',
    experiences: [
      {
        title: 'Technology Monitor | Interdisciplinary Projects Workshop (TPI)',
        date: 'February 2021 - March 2022',
        place: 'Faculty of Engineering, Universidad Nacional de Colombia',
        activities: [
          'Information Architecture & SEO: Digital infrastructure optimization reducing data redundancy by 25% (from 800 to 600 assets), improving loading speed and indexing.',
          'Comprehensive Solutions Development: Design and implementation of high-performance interactive interfaces and feedback systematization through backend with Google Apps Script.',
          'Talent Management & Collaboration: Technical integration of the Quanticon Valley team, deployment of new visual identity and management of large data volumes for groups of more than 160 people.'
        ],
        stack: ['React', 'Next.js', 'SEO', 'Google Apps Script', 'HTML/CSS']
      },
      {
        title: 'Assistant Teaching Student | Bogotá Campus (UNAL)',
        date: 'March 2022 - July 2022',
        place: 'Academic Direction, Universidad Nacional de Colombia',
        activities: [
          'Backend Engineering: Architecture and deployment of server infrastructure for automated grade management, eliminating manual processing and ensuring data integrity.',
          'Digital Continuity: Technical operation of virtual learning platforms, managing network and communications infrastructure for uninterrupted content delivery.'
        ],
        stack: ['Node.js', 'Google Apps Script', 'Infrastructure', 'Automation']
      },
      {
        title: 'Junior Instructor | Faculty of Economic Sciences (UNAL)',
        date: 'February 2021 - August 2021',
        place: 'UIFCE, Universidad Nacional de Colombia',
        activities: [
          'High-Impact Training: Technical training of 44 professionals, designing autonomous learning systems for specialized software adoption.',
          'Team Leadership: Coordination of technical teams of more than 30 people, optimizing internal communication and achievement of objectives with motivation and monitoring tools.'
        ],
        stack: ['Training', 'Learning systems', 'Team management']
      },
      {
        title: 'Frontend Developer | Innovate',
        date: 'September 2021 - December 2021',
        place: 'Faculty of Engineering, Universidad Nacional de Colombia',
        activities: [
          'Interface Refactoring: Visual redesign under institutional regulations, balancing modern aesthetics with optimized technical usability.'
        ],
        stack: ['UI/UX', 'Frontend', 'Institutional regulations']
      }
    ],
    educations: [
      {
        title: 'Agricultural Engineering',
        date: 'August 2019 - Present',
        place: 'Universidad Nacional de Colombia',
        description: `Focus: Specialization in the digitalization of the agro-industrial sector, integrating rural infrastructure design with automation and process control.

Differentiator: Application of engineering principles for efficient management of water resources and machinery through data use.`
      },
      {
        title: 'Agronomic Engineering',
        date: 'January 2016 - July 2019',
        place: 'Universidad Nacional de Colombia',
        description: `Focus: Deep analysis of production and agro-food transformation systems, with emphasis on yield optimization through biotic and abiotic factors.

Differentiator: Ability to interpret the biological language of the field and translate it into scalable technical models.`
      },
      {
        title: 'Junior Programmer',
        date: 'March 2021 - December 2021',
        place: 'Misión TIC 2022',
        description: `Focus: Intensive software development training oriented to solving real problems and digital economic reactivation.

Differentiator: Mastery of robust programming fundamentals for building tools with immediate impact in the industry.`
      }
    ]
  },
  portfolio: {
    title: 'Portfolio',
    subtitle: 'Featured projects combining agricultural engineering with software development',
    viewArchive: 'View project archive',
    viewCase: 'View case',
    visit: 'Visit',
    filters: {
      all: 'All',
      crops: 'Crops',
      design: 'Design',
      programming: 'Programming',
      eduDev: 'Education & Development'
    },
    projects: [
      {
        id: 'SaludVault',
        title: 'SaludVault Web',
        date: 'February 2026',
        category: 'programming',
        image: '/portfolio/portfolio-20.jpg',
        url: 'https://salud-vault.vercel.app/en',
        owner: 'Personal Project',
        ownerRole: 'Product Owner · Web Developer · UX',
        description: 'SaludVault is a web application to manage health information securely and privately.',
        techStack: ['Next.js', 'Tailwind CSS', 'JavaScript', 'Vercel'],
        metric: '500+ visitors in the first month',
        span: 'md:col-span-1',
        rows: 'md:row-span-2',
        featured: true,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'amaderarte',
        title: 'Amaderarte Web',
        date: 'January 2026',
        category: 'programming',
        image: '/portfolio/portfolio-19.jpg',
        url: 'https://amaderarte.vercel.app',
        owner: 'Personal Project',
        ownerRole: 'Product Owner · Web Developer · UX',
        description: 'Amaderarte is a web application that allows you to explore and purchase unique wooden art pieces created by artisans. The platform showcases a diverse collection of sculptures, furniture and decorative objects, offering a smooth shopping experience for enthusiasts and collectors.',
        techStack: ['Next.js', 'Tailwind CSS', 'JavaScript', 'Vercel'],
        metric: '500+ visitors in the first month',
        span: 'md:col-span-2',
        rows: 'md:row-span-1',
        featured: true,
        projectJourneys: [
          {
            title: 'Call',
            body: 'Artisans needed a digital channel that could turn unique pieces into real sales without losing the essence of the craft.'
          },
          {
            title: 'Conflict',
            body: 'Visibility was limited and the physical catalog created friction for buyers outside the local reach.'
          },
          {
            title: 'Transformation',
            body: 'A platform was built focused on visual discovery, fast navigation and a simple purchase flow.'
          },
          {
            title: 'Result',
            body: 'The experience reduced friction and increased reach, achieving more than 500 visitors in the first month.'
          },
          {
            title: 'Return',
            body: 'The workshop was left with a scalable showcase that allows growing the offer and measuring commercial impact.'
          }
        ]
      },
       {
        id: 'dynamicMaps',
        title: 'Dynamic Maps with QGIS and Three.js',
        date: 'March 2023',
        category: 'programming',
        image: '/portfolio/portfolio-17.jpg',
        owner: 'Irrigation Engineering',
        ownerRole: 'University course',
        description: '3D visualization of terrain models and composite maps generated in QGIS, rendered in Three.js to explore layers and relief in the browser.',
        techStack: ['QGIS', 'Three.js', 'WebGL', 'JavaScript'],
        metric: '2 interactive 3D maps',
        span: 'md:col-span-2',
        rows: 'md:row-span-2',
        featured: true,
        maps: [
          {
            title: 'Composite map',
            description: 'Combined layers with texture and relief.',
            src: '/Mapas%203D/Mapa%20Compuesto/Modelo3DNilo.html',
          },
          {
            title: 'Digital elevation model',
            description: 'Topographic relief for slope analysis.',
            src: '/Mapas%203D/Modelo%20de%20Elevaci%C3%B2n%20del%20terreno/Modelo3DNilo.html',
          },
        ],
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'teatroTierra',
        title: 'Teatro Tierra Web Page',
        date: 'June 2024',
        category: 'programming',
        image: '/portfolio/portfolio-18.jpg',
        url: 'https://teatrotierra.org/',
        owner: 'Claudia Sánchez',
        ownerRole: 'Executive Producer',
        description: 'Institutional website for Teatro Tierra.',
        techStack: ['WordPress', 'PHP', 'CSS'],
        metric: 'Website in production',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'ieeeWebsite',
        title: 'IEEE Student Branch Website',
        date: 'January 2023',
        category: 'programming',
        image: '/portfolio/portfolio-16.jpg',
        url: 'https://ieeeunal.github.io/Pagina_Web/',
        owner: 'IEEE UNAL',
        ownerRole: 'University student group',
        description: 'Official website of the IEEE UNAL student branch.',
        techStack: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
        metric: 'Website in production',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'catedraJeg',
        title: 'JEG Chair Website',
        date: 'July 2022',
        category: 'eduDev',
        image: '/portfolio/portfolio-15.jpg',
        url: 'http://www.catedras-bogota.unal.edu.co/catedra-jorge-eliecer-gaitan/2022-1',
        owner: 'Universidad Nacional',
        ownerRole: 'University course',
        description: 'Website of the Jorge Eliécer Gaitán Chair.',
        techStack: ['Joomla', 'PHP', 'MySQL'],
        metric: 'Website in production',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'innovate',
        title: 'Innovate Website',
        date: 'December 2021',
        category: 'eduDev',
        image: '/portfolio/portfolio-14.jpg',
        url: 'https://ingenieria.unal.edu.co/innovate',
        owner: 'Universidad Nacional',
        ownerRole: 'Research group',
        description: 'Website of the Innovate research group.',
        techStack: ['Joomla', 'PHP', 'CSS'],
        metric: 'Website in production',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'deleite',
        title: 'Deleite Restaurant',
        date: 'December 2021',
        category: 'programming',
        image: '/portfolio/portfolio-13.jpg',
        url: 'https://restaurante-deleite.herokuapp.com/',
        owner: 'Misión TIC & UTP',
        ownerRole: 'Final project',
        description: 'Restaurant management system developed as a final project.',
        techStack: ['React', 'Node.js', 'MongoDB', 'Heroku'],
        metric: 'Academic project completed',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'tpi',
        title: 'TPi Website',
        date: 'August 2021',
        category: 'eduDev',
        image: '/portfolio/portfolio-7.jpg',
        owner: 'Universidad Nacional',
        ownerRole: 'University course',
        description: 'Website of the Interdisciplinary Projects Workshop.',
        techStack: ['Joomla', 'PHP', 'CSS'],
        metric: 'Website in production',
        featured: false,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      },
      {
        id: 'cilantro',
        title: 'Cilantro Cultivation',
        date: 'June 2016',
        category: 'crops',
        image: '/portfolio/portfolio-2.jpg',
        owner: 'Jairo Cuervo',
        ownerRole: 'Professor',
        description: 'Academic project for cilantro production with sustainable techniques.',
        techStack: ['Agriculture', 'Integrated crop management'],
        metric: 'Academic project completed',
        span: 'md:col-span-1',
        rows: 'md:row-span-1',
        featured: true,
        projectJourneys: [
          { title: 'Call', body: 'To be defined.' },
          { title: 'Conflict', body: 'To be defined.' },
          { title: 'Transformation', body: 'To be defined.' },
          { title: 'Result', body: 'To be defined.' },
          { title: 'Return', body: 'To be defined.' }
        ]
      }
    ]
  },
  projectLayout: {
    caseStudy: 'Case study',
    viewProject: 'View project',
    process: 'The process',
    trustBar: [
      'On-time delivery',
      'Direct communication',
      'Clean code',
      'Post-launch support'
    ],
    ctaNeed: 'Need something similar?',
    ctaTitle: 'Schedule a free consultation',
    ctaDesc:
      '30 minutes to understand your project and propose a clear path to results.',
    ctaButton: 'Contact now',
    ctaExploreLabel: 'Explore more',
    ctaExploreTitle: 'View other projects',
    ctaExploreDesc:
      'Discover more case studies and the impact I have generated for other clients.',
    ctaExploreButton: 'View portfolio',
    metrics: [
      { value: 500, suffix: '+', label: 'Visitors', sub: 'first month' },
      { value: 3, suffix: 's', label: 'Load', sub: 'average time' },
      { value: 40, suffix: '%', label: 'Conversion', sub: 'estimated improvement' },
      { value: 1, suffix: '', label: 'Month', sub: 'of development' }
    ],
    testimonial: {
      quote:
        'The platform completely transformed how we showcase our work. Online sales exceeded our expectations from the first month.',
      author: 'Amaderarte Client'
    }
  },
  contact: {
    title: "Let's talk about",
    subtitle: 'Business',
    phase: 'Ready to transform ideas into realities?',
    CTA1: "Let's connect ",
    CTA2: "and create something extraordinary.",
    form: {
      name: 'Name',
      email: 'Email',
      subject: 'Subject',
      phaseMessage: 'Send a',
      message: 'Message',
      send: 'Send Message',
      reset: 'Reset',
      sending: 'Sending...',
      success: 'Your message has been sent!',
      error: 'There was an error sending your message'
    }
  },
  footer: {
    rights: 'All rights reserved',
    designed: 'Designed by'
  }
};